apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: zipkin-app

---

apiVersion: v1
kind: Service
metadata:
  name: delay-service
  namespace: default
spec:
  ports:
    - port: 8080
  selector:
    name: delay-app

---

apiVersion: v1
kind: Service
metadata:
  name: feign-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: feign-app
